'use strict';

const raven = require('raven');

const packageJson = require('../../package.json');

// using secret key should be safe in this context according to
// https://docs.sentry.io/clients/javascript/config/#optional-settings
const RAVEN_DSN =
  'https://a97942abe07045b09c56216032d17da5:c442690d11f244d6b358ae057070917e@sentry.io/116459';

let isInitialized = false;
let ravenClient;

exports.init = function init() {
  let releaseJson;
  try {
    // use sentry only in release builds (release.json is generated by gulp)
    releaseJson = require('../../release.json'); // eslint-disable-line global-require
  } catch (error) {
    // empty
  }
  if (!releaseJson) {
    return;
  }

  ravenClient = new raven.Client(RAVEN_DSN, {
    tags: {
      app_version: packageJson.version,
      git_rev: releaseJson.git_rev,
      platform: process.platform,
    },
  });
  ravenClient.install();
  isInitialized = true;
};

// Send an error to sentry if raven is correctly initialized.
// Do nothing otherwise.
exports.capture = function capture(error, callback) {
  if (isInitialized && ravenClient) {
    ravenClient.captureException(error, callback);
  } else {
    process.nextTick(callback);
  }
};
